### DEFAULT SETTINGS ###
#address = "127.0.0.1"
#port = 5600
#cors = []
#
#[custom_static]
[server.custom_static]
aw-watcher-media-player = "~/.config/activitywatch/aw-watcher-media-player/visualization"
